Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "fitness-vm"

  #repo kopiram not v vm
  config.vm.synced_folder "../../", "/projekt"

  #nastavitve virtualne masine
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 4096
    vb.cpus = 2
  end

  #provision skripta
  config.vm.provision "shell", path: "provision.sh"   
end


