Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "fitness-vm"

  # Private IP for accessing the app
  config.vm.network "private_network", ip: "192.168.56.80"

  # Sync the whole repo (fitness-project) into VM
  config.vm.synced_folder "../../", "/opt/fitness-project", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision.sh"
end
